#!/usr/bin/env python3
from apps.cli import main
import sys
try:
    sys.exit(main())
except (ValueError, RuntimeError, OSError) as exc:
    print('OpenNet: ' + str(exc), file=sys.stderr)
    sys.exit(1)
