'use strict';
const $=id=>document.getElementById(id);
const ns='http://www.w3.org/2000/svg';
let token='',state=null,selected='node-a',lastEvent=0,graphSignature='',socket;
const nodeElements=new Map();
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function svg(tag,attrs){const e=document.createElementNS(ns,tag);for(const [k,v]of Object.entries(attrs))e.setAttribute(k,v);return e;}
function position(n,i){return {x:n.x??100+(i%4)*200,y:n.y??90+Math.floor(i/4)*130};}
async function post(path,data){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-OpenNet-Token':token},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw Error(result.error||'Request failed');return result;}
function inspect(event){$('result').textContent=JSON.stringify(event,null,2);$('console').scrollIntoView({behavior:'smooth',block:'nearest'});}
function renderGraph(){const signature=JSON.stringify(state.nodes.map(n=>[n.id,n.x,n.y]))+JSON.stringify(state.links.map(l=>[l.source,l.target]));
 if(signature!==graphSignature){graphSignature=signature;$('graph').replaceChildren();nodeElements.clear();
 const map=new Map(state.nodes.map((n,i)=>[n.id,position(n,i)]));
 state.links.forEach((l,i)=>{const a=map.get(l.source),b=map.get(l.target);$('graph').append(svg('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,id:'edge-'+i,class:'edge'}));});
 state.nodes.forEach((n,i)=>{const {x,y}=position(n,i);const g=svg('g',{transform:`translate(${x},${y})`,tabindex:0,role:'button','aria-label':n.id});g.append(svg('rect',{x:-62,y:-28,width:124,height:60}));const name=svg('text',{y:-3});name.textContent=n.id;const address=svg('text',{y:16,class:'address'});address.textContent=n.address;g.append(name,address);const choose=()=>{selected=n.id;renderRoutes();renderGraph();};g.addEventListener('click',choose);g.addEventListener('keydown',e=>{if(e.key==='Enter')choose();});$('graph').append(g);nodeElements.set(n.id,g);});
 }
 state.nodes.forEach(n=>nodeElements.get(n.id).setAttribute('class',`node ${n.role} ${n.status.toLowerCase()} ${n.id===selected?'chosen':''}`));
 state.links.forEach((l,i)=>$('edge-'+i).setAttribute('class','edge'+(!l.enabled?' disabled':'')));
 $('selected').textContent=selected+' · '+(state.nodes.find(n=>n.id===selected)?.status||'unknown');
}
function pulse(event){const a=state.nodes.find(n=>n.id===event.node),b=state.nodes.find(n=>n.address===event.detail);if(!a||!b)return;const start=position(a,state.nodes.indexOf(a)),end=position(b,state.nodes.indexOf(b));const c=svg('circle',{cx:start.x,cy:start.y,r:5,class:'pulse'});c.addEventListener('click',()=>inspect(event));$('graph').append(c);const t=performance.now();function step(now){const f=Math.min((now-t)/1100,1);c.setAttribute('cx',start.x+(end.x-start.x)*f);c.setAttribute('cy',start.y+(end.y-start.y)*f);if(f<1)requestAnimationFrame(step);else c.remove();}requestAnimationFrame(step);}
function renderRoutes(){$('routing-mode').textContent=state.routing_mode==='static'?'Static':'Dijkstra';$('route-title').textContent=selected+' · installed paths';const tbody=$('routes');tbody.replaceChildren();Object.entries(state.routes[selected]||{}).filter(([_,p])=>p.length>1).forEach(([dst,path])=>{const tr=el('tr');[dst,path[1],String(path.length-1)].forEach(s=>tr.append(el('td',s)));tr.title=path.join(' → ');tbody.append(tr);});}
function renderNodes(){const tbody=$('node-table');tbody.replaceChildren();state.nodes.forEach(n=>{const tr=el('tr');const title=el('td',n.id);title.append(el('small',n.address));tr.append(title,el('td',n.role));const status=el('td');status.append(el('span','● '+n.status,'status '+n.status.toLowerCase()));tr.append(status,el('td',String(n.pid??'—')),el('td',n.heartbeat_age_s.toFixed(1)+'s'));const actions=el('td');const stopped=n.status==='FAILED';const button=el('button',stopped?'Restart':'Kill process');button.onclick=async()=>{button.disabled=true;try{await post('/api/fault',{node:n.id,action:stopped?'restart':'kill'});}catch(e){$('result').textContent=e.message;}finally{button.disabled=false;}};actions.append(button);tr.append(actions);tbody.append(tr);});}
function renderEvents(){const show=$('show-heartbeats').checked;const events=state.events.filter(e=>show||!['heartbeat','routes_updated'].includes(e.event)).slice(-60).reverse();$('event-list').replaceChildren();events.forEach(e=>{const row=el('div',undefined,'event');row.append(el('span',new Date(e.time_ms).toLocaleTimeString(),'time'),el('span',e.event,'kind'),el('span',e.node||'controller'),el('span',e.id?'#'+e.id+' '+(e.detail||''):e.detail||'','detail'));row.onclick=()=>inspect(e);$('event-list').append(row);});}
function update(s){state=s;$('active').textContent=s.nodes.filter(n=>n.status==='ACTIVE').length+' / '+s.nodes.length;$('sent').textContent=(s.metrics.sent||0).toLocaleString();$('success').textContent=s.metrics.successful||0;$('dropped').textContent=s.metrics.dropped||0;$('transport').textContent=s.transport.toUpperCase()+' OVERLAY';$('uptime').textContent='Session '+Math.floor(s.uptime_s/60)+'m '+Math.floor(s.uptime_s%60)+'s';
 if(!$('source').options.length){s.nodes.forEach(n=>{const o=el('option',n.id);o.value=n.id;$('source').append(o);});$('source').value=s.source;selected=s.source;}
 renderGraph();renderRoutes();renderNodes();renderEvents();
 const fresh=s.events.filter(e=>e.event_seq>lastEvent);if(lastEvent)fresh.filter(e=>e.event==='forward').slice(-30).forEach(pulse);lastEvent=Math.max(lastEvent,...s.events.map(e=>e.event_seq));
}
$('request').onsubmit=async e=>{e.preventDefault();$('send').disabled=true;$('result').textContent='Waiting for the overlay response…';try{const result=await post('/api/request',{kind:$('kind').value,target:$('target').value.trim(),source:$('source').value,ttl:Number($('ttl').value),payload:$('payload').value,path:$('payload').value||'/'});let out=result.ok?'SUCCESS':'FAILED';out+='  #'+(result.id||'DNS cache');if(result.rtt_ms!==undefined)out+='  '+result.rtt_ms.toFixed(3)+' ms RTT';out+='\n'+(result.payload||result.error||'');if(result.cached)out+='\nDNS cache hit';if(result.trace){out+='\n\nObserved receive events:\n';out+=result.trace.filter(e=>e.event==='receive').sort((a,b)=>a.time_ms-b.time_ms).map(e=>`${e.node.padEnd(12)} type=${e.type} ttl=${e.ttl}`).join('\n');}$('result').textContent=out;}catch(error){$('result').textContent=error.message;}finally{$('send').disabled=false;}};
$('show-heartbeats').onchange=()=>state&&renderEvents();$('theme').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('opennet-theme',document.body.classList.contains('light')?'light':'dark');};if(localStorage.getItem('opennet-theme')==='light')document.body.classList.add('light');
async function connect(){try{token=(await(await fetch('/api/session')).json()).token;socket=new WebSocket(`${location.protocol==='https:'?'wss:':'ws:'}//${location.host}/ws?token=${encodeURIComponent(token)}`);socket.onopen=()=>{$('connection').textContent='● LIVE CONNECTION';};socket.onmessage=e=>update(JSON.parse(e.data));socket.onclose=()=>{$('connection').textContent='Disconnected · retrying';setTimeout(connect,2000);};socket.onerror=()=>socket.close();}catch(e){$('connection').textContent='Controller unavailable';setTimeout(connect,2000);}}
connect();
