$ErrorActionPreference = "Stop"
Write-Host "OpenNet uses Linux/POSIX sockets. Choose WSL2 Ubuntu or Docker Desktop."
Write-Host ""
Write-Host "WSL2 (run in Administrator PowerShell if WSL is not installed):"
Write-Host "  wsl --install -d Ubuntu"
Write-Host "Restart Windows if prompted, then open Ubuntu and follow SETUP_WINDOWS.md."
Write-Host ""
Write-Host "Docker Desktop (Linux containers):"
Write-Host "  docker compose up --build"
Write-Host "Dashboard: http://localhost:3000"
